### ISSUE TITLE
installable app? (not in app store)

### ISSUE THREAD

**Issue by lsloan** [palaniraja/mclock#10]
Please provide an installable version of the app.  The link to the Apple app store no longer works. Not everyone who would like to use this know how to build the app with Xcode.  If possible, add a website address from where it can be downloaded.  Otherwise, make releases on GitHub and attach a compiled app, ready to install and run.

**Comment by palaniraja** [comment]
Thanks for reporting. 

We forgot to update our CC on apple account, it could be the reason why it is not listed now. Though we have updated our CC with Apple. Feel free to download the binary temporarily from - https://github.com/palaniraja/mclock/blob/master/binary/mclock.zip 

I am not sure whether this is the latest version, will update it when I get some time. Feel free to buy later from app store when I resolve listing.

**Comment by lsloan** [comment]
Thanks for the suggestion!

I didn't notice the "binary" directory at first.  It turns out that the app in the zip file there is the same as the version I have already installed, v2.0.

I was looking for whether there was an update.  The version of mclock I've been using still has a problem that it's off by part of a minute.  I'm using the format string "`HH:mm​'Z'`".  

I notice in the code that there's a condition for updating every second if the format string includes "`s`".  I tried adding that ("`HH:mm:ss​'Z'`"), but it didn't work.  Could the app in the zip file be older than the source code?

FWIW, I'd suggest using GitHub's "releases" feature to make new versions available.  You could then attach a zip file to the release, making them very easy to find.

**Comment by lsloan** [comment]
I see that it's now available in the Apple App Store at: https://apps.apple.com/us/app/mclock/id1076119164

I'm surprised that an updated version (2.2) of mclock is available there for $3.99, but it hasn't been updated here.  Has the clock sync bug (#5 & #8) been fixed in the new app store version?
