### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by aturner995** [palaniraja/mclock#2]
Would it be possible to have a preference for update frequency (or just have a version where it updates every second)? I really like this app and it's great to have the second clock in my status bar but it would be nice for the minute field to update quickly after the minute changes.

**Comment by palaniraja** [comment]
Fixed in v2.2 (submitted to appstore today). Should be available in 2-3 weeks.

If you include the second modifier 's' your time is updated every second. Else it will get updated every minute the old way.
