### ISSUE TITLE
Menu with timezones

### ISSUE THREAD

**Issue by jbenet** [palaniraja/mclock#3]
would be nice to have a menu with timezones. basically something like:

```
----------------------------------
| 10:01 GMT+7 PDT |
----------------------------------
| 02:01 GMT+9 JST Tokyo          |
| 10:01 GMT-7 PDT San Francisco  |
| 13:01 GMT-4 EDT New York       |
| 18:01 GMT+1 CET Paris, Berlin  |
----------------------------------
```
- editable TZs
- editable TZ Text (e.g. "GMT+9 JST Tokyo" above)
- maybe can select order of the tokens

**Comment by palaniraja** [comment]
Hi Juan,

Thank you for the valuable feedback. 

I'm not currently working on new version, though I've a plan to update it with more feature and keep the app simple to use.

Star the repo, so you will get notified when I start working on it.
