### ISSUE TITLE
Time out of sync with system clock

### ISSUE THREAD

**Issue by paulgalbraith** [palaniraja/mclock#5]
Hi,

I bought this app from the Mac App Store but the time is out of sync with the system clock - the minute digit changes about 10+ seconds after the system - I expected them to be precisely in sync. 

It would also be good to have custom text instead of the zone prefix (i.e. New York instead of EST).

Thanks.

**Comment by palaniraja** [comment]
Next update will have fix for this issue. Closing it for now. Reopen if you still have the issue. 

Note, expect the update in 2-3 weeks time considering app store review process.
